# -*- coding: utf-8 -*-
"""aitest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YO9yQkuCdamPDawKIAN_9jah13cUjq6O
"""

! nvidia-smi

! git clone https://github.com/AlexeyAB/darknet.git
! apt install g++

"""Draknet環境建制"""

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile

! head Makefile

"""調用配置"""

!/usr/local/cuda/bin/nvcc --version

!make

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

# Commented out IPython magic to ensure Python compatibility.
def imShow(path): #列印功能
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image=cv2.imread(path)
  height,width=image.shape[:2]
  resized_image = cv2.resize(image, (3*width, 3*height), interpolation = cv2.INTER_CUBIC)
  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

def upload():
  from google.colab import files
  uploaded = files.upload() 
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print ('saved file', name)

def download(path):
  from google.colab import files
  files.download(path)

"""prerained weight
obj.name - darknet/data

!./darknet detector test <path to .data file> <path to config> <path to weights> <path to image>
"""

# run darknet detection
!./darknet detect cfg/yolov4-light.cfg /content/drive/MyDrive/yolov4-light_last.weights 1.jpg
# show result
#imShow('predictions.jpg')
!./darknet detector test data/light.data cfg/yolov4-light.cfg /content/drive/MyDrive/yolov4-light_last.weights data/person.jpg -i 0 -thresh 0.25

!wget /content/drive/MyDrive/yolov4-light_last.weights

b

!./darknet detector train data/light.data cfg/yolov4-light.cfg yolov4.conv.137 -dont_show

!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/1.jpg

# 印出來
imShow('predictions.jpg')

!cd ..
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet

!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights /mydrive/aihw/3.jpg
imShow('predictions.jpg')

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show data/test.mp4 -i 0 -out_filename data/results.avi

#download('results.avi')

